server:
  port: 7070
spring:
  cloud:
    stream:
      bindings:
#        foodOrdersChannel:
#          destination: foodOrders
#        output:
#          destination: foodOrders
        input:
          destination: foodOrders
          group: foodOrdersIntakeGroup
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: test
