server:
  port: 7070
spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
      env:
        enabled: true
    stream:
      bindings:
        #        foodOrdersChannel:
        #          destination: foodOrders
        #        output:
        #          destination: foodOrders
        input:
          destination: foodOrders
          group: foodOrdersIntakeGroup

  # connect to Rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: rabbit-app

# actuator endpoints are not exposed by default
management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers

# create queue
queue:
  name: kimhab-queue-test

endpoints:
  spring:
    cloud:
      bus:
        env:
          enabled: true
        refresh:
          enabled: true