server:
  port: 7070
spring:
  cloud:
    stream:
      bindings:
#        foodOrdersChannel:
#          destination: foodOrders
#        output:
#          destination: foodOrders
        input:
          destination: foodOrders
          group: foodOrdersIntakeGroup
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: rabbit-app

# actuator endpoints are not exposed by default
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
queue:
  name: kimhab-queue-test


