
server:
  port: 0
spring:
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: foodOrders
          group: foodOrdersIntakeGroup
  application:
    name: rb-consumer
  profiles:
    active: uat