server:
  port: 8080
management:
  security:
    enabled: false
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: rb-publisher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
     uri: http://localhost:8888
    # cloud stream
    stream:
      bindings:
        foodOrdersChannel:
          destination: foodOrders
      default:
        contentType: application/json
